#!/bin/bash

# Game Shell Test Suite - Quick Commands

echo "Game Shell Test Suite"
echo "====================="
echo ""
echo "Available commands:"
echo ""
echo "1. Install dependencies:"
echo "   cd tests"
echo "   npm install && npx playwright install chromium"
echo ""
echo "2. Run all tests:"
echo "   cd tests && npm test"
echo ""
echo "3. Run specific test suites:"
echo "   cd tests && npm run test:games     # Test actual games"
echo "   cd tests && npm run test:generic   # Test generic canvases"
echo ""
echo "4. Debug tests:"
echo "   cd tests && npm run test:headed    # Show browser"
echo "   cd tests && npm run test:ui        # Interactive UI"
echo ""
echo "5. View test pages manually:"
echo "   python -m http.server 8000"
echo "   # Then open:"
echo "   # http://localhost:8000/tests/test-tall-canvas.html"
echo "   # http://localhost:8000/tests/test-wide-canvas.html"
echo ""
